[package]

name = "rusteroids"
version = "0.1.0"
authors = [ "benbrunton@hotmail.com" ]


[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs"